(function (root) {
  'use strict';
  const VERSION = 1;
  const chapters = [
    ['01 · Bien démarrer', [
      ['Bienvenue dans MindSet', '<p>MindSet est ton espace personnel : des boîtes pour séparer les projets, des dossiers pour les organiser, des notes et de l’audio pour développer tes idées. Tout est enregistré sur cet ordinateur.</p><p>Ce guide est une vraie boîte : tu peux le parcourir, le modifier ou le supprimer. Tes autres boîtes restent indépendantes. Le bouton Guide MindSet de l’accueil permet de le retrouver ou de le recréer.</p>'],
      ['Créer et organiser', '<p>Depuis l’accueil, choisis Nouvelle boîte. Donne-lui un nom et, si tu le souhaites, un code. Dans une boîte, crée des dossiers, des notes et des documents audio.</p><p>Utilise l’explorateur et le clic droit pour renommer, déplacer, copier ou supprimer des éléments. Le glisser-déposer réorganise les dossiers. Les onglets et les signets donnent accès à tes documents favoris.</p>'],
      ['Retrouver une information', '<p>La recherche de la boîte et le sélecteur Ctrl + K permettent de retrouver un document. Le plan affiche les titres de la note. Les panneaux latéraux se masquent pour laisser plus de place à l’écriture.</p>'],
    ]],
    ['02 · Écrire et mettre en forme', [
      ['Le menu / et les annotations', '<p>Dans un paragraphe vide, tape / pour choisir un titre, une liste, une tâche, une citation, une annotation, du code, un séparateur ou un saut de page. Recherche une commande, utilise les flèches puis Entrée. Échap ferme le menu.</p><p>Sélectionne du texte pour faire apparaître la barre de mise en forme. La barre principale propose aussi polices, couleurs, surlignage, alignement et styles de titres.</p>'],
      ['Retours à la ligne et pages', '<p>Entrée crée un paragraphe. Maj + Entrée crée un retour à la ligne dans le même paragraphe. Après un titre, Entrée permet de poursuivre en texte normal. Sur une ligne de liste vide, Entrée permet de sortir de la liste.</p><p>L’écriture reste continue, même dans la vue papier. Les pages automatiques sont calculées à l’impression : elles ne déplacent pas le curseur pendant la frappe. Pour imposer une nouvelle page, utilise le saut de page du menu /.</p>'],
      ['Titres, listes, images et tableaux', '<p>Les titres structurent le plan. Les listes peuvent être simples, numérotées ou à cocher. Les images et les tableaux collés sont conservés dans les notes. Ctrl + Z annule la dernière modification ; Ctrl + Y ou Ctrl + Maj + Z la rétablit.</p><p>Les paramètres permettent de personnaliser les styles, les couleurs, les marges et les polices. Les polices installées par toi restent soumises à leur propre licence.</p>'],
      ['Exporter une note', '<p>Le menu d’export propose le texte, le document compatible Word et le PDF ou l’impression. Ces exports servent à lire et partager une note. Pour restaurer une boîte entière dans MindSet, utilise un fichier .mindset depuis l’accueil.</p>'],
    ]],
    ['03 · Vue arbre et audio', [
      ['Se déplacer dans la vue arbre', '<p>La vue arbre représente les vrais dossiers et documents de la boîte. Change son orientation, déplie ou replie les branches et utilise les commandes de zoom. Le bouton Recentrer ramène le graphe à son point de départ lorsque tu t’es éloigné.</p><p>Ouvre un document depuis le graphe puis retourne à l’écriture avec le bouton de retour à la note.</p>'],
      ['Enregistrer et écouter', '<p>Crée un document audio pour enregistrer avec le microphone ou importer un fichier sonore. Autorise le microphone lorsque cela est demandé. Tu peux nommer et organiser les clips, puis les écouter dans MindSet.</p><p>Les sauvegardes .mindset comprennent les octets audio, et pas seulement leurs noms. Termine ton enregistrement avant d’exporter. Un export incomplet est refusé lorsqu’un clip référencé manque.</p>'],
    ]],
    ['04 · Sauvegarder et protéger', [
      ['Exporter une boîte ou tout sauvegarder', '<p>Depuis l’accueil, le bouton Exporter de chaque boîte produit un fichier .mindset. Sauvegarder toutes les boîtes réunit les boîtes et leur audio dans un seul fichier. MindSet reste ouvert.</p><p>Choisis un emplacement que tu retrouveras, puis garde une copie sur un autre support. Une sauvegarde contient le contenu au moment de l’export. Les préférences d’affichage et les polices de cet ordinateur ne font pas partie de ce fichier.</p><p>Limite : 256 Mo par fichier. Au-delà, exporte les boîtes séparément. Le téléchargement du navigateur peut nécessiter une confirmation ; vérifie que le fichier existe avant de désinstaller quoi que ce soit.</p>'],
      ['Importer des boîtes', '<p>À côté de Nouvelle boîte, choisis Importer des boîtes puis un fichier .mindset. MindSet vérifie le fichier et présente un résumé avant l’import.</p><p>Les boîtes absentes sont ajoutées. Celles qui portent déjà le même identifiant sont conservées sans être écrasées, même si leurs noms ont changé. Ce bouton ajoute les boîtes manquantes ; il ne remplace pas une version existante par une ancienne sauvegarde.</p><p>Les notes, dossiers, images intégrées et clips audio sont restaurés. Les images qui pointent vers un site externe dépendent toujours de ce site.</p>'],
      ['Boîtes protégées', '<p>Un code protège le contenu d’une boîte par chiffrement. Garde ce code : il n’existe pas de récupération magique en cas d’oubli. Le nom de la boîte reste visible sur l’accueil et dans les sauvegardes.</p><p>L’export conserve le chiffrement des notes et de l’audio. Il ne retire pas le code. Une très ancienne boîte protégée doit d’abord être ouverte pour terminer sa migration. Si MindSet signale un audio non chiffré, ouvre la boîte, attends la fin de l’opération et réessaie.</p>'],
      ['Si une boîte semble manquer', '<p>Vérifie d’abord que tu utilises la même installation et le même compte Windows. Une version de développement utilise désormais un espace séparé. Le second lancement de la même installation ramène sa fenêtre existante.</p><p>Si MindSet ne peut pas lire son stockage, il affiche une erreur et bloque les écritures au lieu de créer un espace vide par-dessus. Ne supprime pas les données locales pour résoudre ce problème.</p>'],
    ]],
    ['05 · Application et nouveautés', [
      ['Mises à jour et réinstallation', '<p>Le parcours prévu reste Rechercher → Télécharger → Redémarrer. Une mise à jour ne doit être installée qu’après la sauvegarde des données. La nouvelle gestion vérifie la version réellement installée et affiche les erreurs d’installation.</p><p>Sur cet ordinateur, Windows a bloqué un installeur non signé. Réinstaller le même fichier ne garantit pas de résoudre ce blocage. La distribution de cette nouvelle version attend une solution de confiance Windows. Aucun abonnement n’est nécessaire pour utiliser MindSet ; aucun service de signature payant n’a été souscrit.</p><p>Avant une désinstallation, garde une sauvegarde .mindset vérifiée. Ne choisis jamais une option de suppression des données si tu veux les conserver.</p>'],
      ['Raccourcis utiles', '<ul><li>Ctrl + K : sélecteur de documents.</li><li>Ctrl + N dans une boîte : nouvelle note.</li><li>Ctrl + Z : annuler ; Ctrl + Y ou Ctrl + Maj + Z : rétablir.</li><li>Ctrl + C / X / V : copier, couper ou coller le texte, ou les éléments sélectionnés hors de l’éditeur.</li><li>Échap : fermer un menu ou une fenêtre de dialogue.</li><li>Suppr hors de l’éditeur : demander la suppression des éléments sélectionnés.</li></ul>'],
      ['Nouveautés préparées en 1.3.4', '<ul><li>Un seul processus principal par profil ; second lancement ramené à la fenêtre existante.</li><li>Importer et exporter des boîtes, avec leur audio.</li><li>Vérification d’intégrité des fichiers et import sans écrasement.</li><li>Guide organisé, séparé des projets sur l’accueil.</li><li>Protection du stockage en cas d’erreur de lecture.</li><li>Recentrage de la vue arbre.</li><li>Journal SUIVI_MINDSET.txt à la racine du projet.</li></ul><p>Version préparée dans les sources. Cela ne signifie pas qu’un nouvel installeur a été publié ou installé sur ton ordinateur.</p>'],
    ]],
  ];
  function create(uid, now) {
    const stamp = now();
    const item = (type, title, extra) => ({ id: uid(type), type, title, createdAt: stamp, modifiedAt: stamp, ...extra });
    const folders = chapters.map(([title, notes]) => item('folder', title, { children: notes.map(([title, content]) => item('note', title, { content })) }));
    const root = item('folder', 'Guide MindSet', { children: folders });
    return { id: uid('box'), name: 'Guide MindSet', isGuide: true, guideVersion: VERSION, passwordHash: '', createdAt: stamp, modifiedAt: stamp, root, activeItemId: folders[0].children[0].id, expandedIds: [root.id, folders[0].id], selectedIds: [], bookmarkedIds: [], openTabIds: [], viewMode: 'tree', sortMode: 'custom', iconFolderId: root.id, searchQuery: '' };
  }
  root.MindSetGuide = { create, VERSION };
  if (typeof module === 'object' && module.exports) module.exports = root.MindSetGuide;
})(typeof globalThis === 'object' ? globalThis : this);
