(function (root) {
  'use strict';
  const VERSION = 4;
  const chapters = [
    ['01 · Bien démarrer', [
      ['Bienvenue dans MindSet', '<p>MindSet est ton espace personnel : des boîtes pour séparer les projets, des dossiers pour les organiser, des notes et de l’audio pour développer tes idées. Tout est enregistré sur cet ordinateur.</p><p>Ce guide est une vraie boîte : tu peux le parcourir, le modifier ou le supprimer. Tes autres boîtes restent indépendantes. Le bouton Guide MindSet de l’accueil permet de le retrouver ou de le recréer.</p>'],
      ['Créer et organiser', '<p>Depuis l’accueil, choisis Nouvelle boîte. Donne-lui un nom et, si tu le souhaites, un code. Dans une boîte, crée des dossiers, des notes et des documents audio.</p><p>Utilise l’explorateur et le clic droit pour renommer, déplacer, copier ou supprimer des éléments. Le glisser-déposer réorganise les dossiers. Les onglets et les signets donnent accès à tes documents favoris.</p>'],
      ['Retrouver une information', '<p>La recherche de la boîte et le sélecteur Ctrl + K permettent de retrouver un document. Le plan affiche les titres de la note. Les panneaux latéraux se masquent pour laisser plus de place à l’écriture.</p>'],
    ]],
    ['02 · Écrire et mettre en forme', [
      ['Le menu / et les annotations', '<p>Dans un paragraphe vide, tape / pour choisir un titre, une liste, une tâche, une citation, une annotation, du code, un séparateur ou un saut de page. Recherche une commande, utilise les flèches puis Entrée. Échap ferme le menu.</p><p>Sélectionne du texte pour faire apparaître la barre de mise en forme. La barre principale propose aussi polices, couleurs, surlignage, alignement et styles de titres.</p>'],
      ['Retours à la ligne et pages', '<p>Entrée crée un paragraphe. Maj + Entrée crée un retour à la ligne dans le même paragraphe. Après un titre, Entrée permet de poursuivre en texte normal. Sur une ligne de liste vide, Entrée permet de sortir de la liste.</p><p>Le mode Note reste un espace continu. Le mode Livre montre les pages et fait passer le texte automatiquement d’une feuille à la suivante. Pour imposer une nouvelle page, utilise Ctrl + Entrée ou le saut de page du menu /.</p>'],
      ['Titres, listes, images et tableaux', '<p>Les titres structurent le plan. Les listes peuvent être simples, numérotées ou à cocher. Les images et les tableaux collés sont conservés dans les notes. Ctrl + Z annule la dernière modification ; Ctrl + Y ou Ctrl + Maj + Z la rétablit.</p><p>Les paramètres permettent de personnaliser les styles, les couleurs, les marges et les polices. Les polices installées par toi restent soumises à leur propre licence.</p>'],
      ['Exporter une note', '<p>Le menu d’export propose le texte, le document compatible Word et le PDF ou l’impression. Ces exports servent à lire et partager une note. Pour restaurer une boîte entière dans MindSet, utilise un fichier .mindset depuis l’accueil.</p>'],
    ]],
    ['03 · Vue arbre et audio', [
      ['Se déplacer dans la vue arbre', '<p>La vue arbre représente les vrais dossiers et documents de la boîte. Change son orientation, déplie ou replie les branches et utilise les commandes de zoom. Le bouton Recentrer ramène le graphe à son point de départ lorsque tu t’es éloigné.</p><p>Ouvre un document depuis le graphe puis retourne à l’écriture avec le bouton de retour à la note.</p>'],
      ['Enregistrer et écouter', '<p>Crée un document audio pour enregistrer avec le microphone ou importer un fichier sonore. Autorise le microphone lorsque cela est demandé. Tu peux nommer et organiser les clips, puis les écouter dans MindSet.</p><p>Les sauvegardes .mindset comprennent les octets audio, et pas seulement leurs noms. Termine ton enregistrement avant d’exporter. Un export incomplet est refusé lorsqu’un clip référencé manque.</p>'],
    ]],
    ['04 · Sauvegarder et protéger', [
      ['Exporter une boîte ou tout sauvegarder', '<p>Depuis l’accueil, le bouton Exporter de chaque boîte produit un fichier .mindset. Sauvegarder toutes les boîtes réunit les boîtes et leur audio dans un seul fichier. MindSet reste ouvert.</p><p>Choisis un emplacement que tu retrouveras, puis garde une copie sur un autre support. Une sauvegarde contient le contenu au moment de l’export. Les préférences d’affichage et les polices de cet ordinateur ne font pas partie de ce fichier.</p><p>Limite : 256 Mo par fichier. Au-delà, exporte les boîtes séparément. Le téléchargement du navigateur peut nécessiter une confirmation ; vérifie que le fichier existe avant de désinstaller quoi que ce soit.</p>'],
      ['Importer des boîtes', '<p>À côté de Nouvelle boîte, choisis Importer des boîtes puis un fichier .mindset. MindSet vérifie le fichier et présente un résumé avant l’import.</p><p>Les boîtes absentes sont ajoutées. Celles qui portent déjà le même identifiant sont conservées sans être écrasées, même si leurs noms ont changé. Ce bouton ajoute les boîtes manquantes ; il ne remplace pas une version existante par une ancienne sauvegarde.</p><p>Les notes, dossiers, images intégrées et clips audio sont restaurés. Les images qui pointent vers un site externe dépendent toujours de ce site.</p>'],
      ['Boîtes protégées', '<p>Un code protège le contenu d’une boîte par chiffrement. Garde ce code : il n’existe pas de récupération magique en cas d’oubli. Le nom de la boîte reste visible sur l’accueil et dans les sauvegardes.</p><p>L’export conserve le chiffrement des notes et de l’audio. Il ne retire pas le code. Une très ancienne boîte protégée doit d’abord être ouverte pour terminer sa migration. Si MindSet signale un audio non chiffré, ouvre la boîte, attends la fin de l’opération et réessaie.</p>'],
      ['Si une boîte semble manquer', '<p>Vérifie d’abord que tu utilises la même installation et le même compte Windows. Une version de développement utilise désormais un espace séparé. Le second lancement de la même installation ramène sa fenêtre existante.</p><p>Si MindSet ne peut pas lire son stockage, il affiche une erreur et bloque les écritures au lieu de créer un espace vide par-dessus. Ne supprime pas les données locales pour résoudre ce problème.</p>'],
    ]],
    ['05 · Application et nouveautés', [
      ['Mises à jour et réinstallation', '<p>Le parcours prévu reste Rechercher → Télécharger → Redémarrer. Une mise à jour ne doit être installée qu’après la sauvegarde des données. La nouvelle gestion vérifie la version réellement installée et affiche les erreurs d’installation.</p><p>La mise à jour vers 1.3.2 a finalement réussi sur cet ordinateur. Une précédente tentative avait été bloquée par Windows ; la cause de la réussite suivante n’est pas établie. La version 1.3.5 permet à nouveau une distribution personnelle gratuite sans certificat. Les téléchargements sont vérifiés et les protections de Windows restent actives. Aucun abonnement n’est nécessaire pour utiliser MindSet ; aucun service de signature payant n’a été souscrit.</p><p>Avant une désinstallation, garde une sauvegarde .mindset vérifiée. Ne choisis jamais une option de suppression des données si tu veux les conserver.</p>'],
      ['Raccourcis utiles', '<ul><li>Ctrl + K : sélecteur de documents.</li><li>Ctrl + N dans une boîte : nouvelle note.</li><li>Ctrl + Z : annuler ; Ctrl + Y ou Ctrl + Maj + Z : rétablir.</li><li>Ctrl + C / X / V : copier, couper ou coller le texte, ou les éléments sélectionnés hors de l’éditeur.</li><li>Échap : fermer un menu ou une fenêtre de dialogue.</li><li>Suppr hors de l’éditeur : demander la suppression des éléments sélectionnés.</li></ul>'],
      ['Nouveautés préparées en 1.3.4', '<ul><li>Un seul processus principal par profil ; second lancement ramené à la fenêtre existante.</li><li>Importer et exporter des boîtes, avec leur audio.</li><li>Vérification d’intégrité des fichiers et import sans écrasement.</li><li>Guide organisé, séparé des projets sur l’accueil.</li><li>Protection du stockage en cas d’erreur de lecture.</li><li>Recentrage de la vue arbre.</li><li>Journal SUIVI_MINDSET.txt à la racine du projet.</li></ul><p>Version préparée dans les sources. Cela ne signifie pas qu’un nouvel installeur a été publié ou installé sur ton ordinateur.</p>'],
    ]],
  ];
  const bookChapter = ['06 · Mode livre', [
    ['Des feuilles distinctes, un seul texte', '<p>Le bouton Mode livre remplace l’ancien affichage en deux colonnes. Le document commence en A4, avec deux feuilles côte à côte. Quand une feuille est pleine, le texte se poursuit automatiquement sur la suivante. Fais défiler le document pour retrouver les pages suivantes.</p><p>Le bouton moins affiche davantage de feuilles, jusqu’à quatre par rangée. Le bouton plus revient vers une seule feuille. Le menu permet aussi de choisir directement 1, 2, 3 ou 4 pages. Le zoom ne modifie ni le texte ni la taille imprimée.</p><p>Une feuille pâle « Page suivante » est un emplacement d’aperçu : elle n’est pas ajoutée au PDF tant qu’elle ne contient rien. Au début absolu de la note, Retour arrière ne déplace plus le document.</p>'],
    ['Format, orientation et marges', '<p>Choisis Format des pages pour sélectionner A4, A5, A6, A3, Letter, Legal, Executive ou Poche. Les dimensions personnalisées acceptent une largeur et une hauteur de 8 à 60 cm. L’orientation et les quatre marges sont réglables. Il faut garder au moins 4 cm de largeur et de hauteur pour écrire.</p><p>Le format appartient à la note et accompagne son export .mindset. Le nombre de feuilles côte à côte est une préférence de cet ordinateur. Les titres restent entièrement dépliés en mode livre pour montrer tout le contenu imprimable.</p>'],
    ['Sauts de page et PDF', '<p>Entrée crée un paragraphe ; Maj + Entrée crée une ligne dans le même paragraphe. Pour commencer une nouvelle feuille volontairement, utilise Ctrl + Entrée, le bouton Saut de page ou le menu /.</p><p>Exporter en PDF puis Créer le PDF prépare les vraies pages, avec la mise en forme et les images. Dans l’aperçu, Enregistrer PDF sauvegarde le document. Ajouter un titre, une date ou une heure lors de l’export prend de la place et peut modifier les coupures.</p><p>Pour une impression sur papier, choisis le même format, une échelle de 100 % et désactive les en-têtes automatiques du système. L’export compatible Word reprend le format ; Word peut effectuer sa propre pagination. Un tableau ou un bloc indivisible plus haut qu’une feuille peut nécessiter une mise en forme adaptée.</p>'],
  ]];
  chapters.push(bookChapter);
  const writingChapter = ['07 · Écriture et couleurs · 1.3.6', [
    ['Note et Livre', '<p>Chaque document s’ouvre en mode Note : un espace continu pour écrire. Le bouton Livre affiche les vraies feuilles et remplace entièrement l’ancienne vue Feuilles. Le format et les marges choisis pour le livre restent enregistrés dans la note.</p><p>En mode Livre, les feuilles s’adaptent à la largeur et à la hauteur disponibles : une rangée entière reste visible. Le passage de la fin d’une feuille au début de la suivante, sur la même rangée, ne demande plus de remonter. Choisis de une à quatre feuilles côte à côte ; le document défile quand tu passes à la rangée suivante.</p>'],
    ['Zoomer sans changer la police', '<p>En mode Note, utilise Ctrl + molette ou pince le pavé tactile pour agrandir ou réduire l’affichage. Les boutons moins et plus font la même chose. Clique sur le pourcentage pour retrouver 100 %.</p><p>Le zoom visuel va de 50 % à 200 %. Il ne modifie ni la taille de police enregistrée, ni le contenu, ni l’impression. Une taille 13 reste une taille 13. Ce zoom est conservé sur cet ordinateur.</p>'],
    ['Couleur du texte et surlignage', '<p>Sélectionne du texte, ouvre sa palette puis clique sur une couleur : elle s’applique immédiatement. Personnaliser ouvre le sélecteur de couleur ; les changements sont visibles directement. Fermer le sélecteur ou la palette conserve le dernier choix. Aucun bouton de validation supplémentaire n’est nécessaire.</p><p>Le texte et le surlignage possèdent chacun douze couleurs prédéfinies, modifiables dans Paramètres → Apparence, et trois cases de couleurs personnalisées. Les cases se remplissent dans l’ordre : 1, 2, 3, puis la nouvelle couleur remplace la case 1, et ainsi de suite. Reprendre une couleur déjà présente ne la duplique pas. Un déplacement dans le sélecteur mémorise seulement la couleur finale. Enlever le surlignage retire le fond du texte sélectionné.</p>'],
    ['Colorer les puces et les formes', '<p>Double-clique directement sur une puce, un numéro, un tiret, une flèche, un rond, un carré, un triangle ou une case à cocher. La palette propose noir, rouge, bleu, jaune, orange, vert, violet et rose. Le texte de la ligne conserve sa propre couleur.</p><p>Suivre la couleur du texte rétablit la couleur automatique du marqueur : le dernier caractère coloré avant la liste ou l’élément précédent, puis le texte de l’élément si nécessaire. Cela permet aussi d’utiliser d’autres couleurs. Les choix accompagnent la note lors de la sauvegarde et de l’export.</p>'],
    ['Tous les émojis', '<p>Fais un clic droit sur une note, un dossier ou un document audio. Sous les choix rapides, le champ Tous les émojis accepte un émoji collé ou choisi avec Win + . sur Windows. Valide avec Entrée ou le bouton à côté du champ.</p><p>Les drapeaux, les tons de peau et les émojis composés sont conservés en entier. L’option Sans icône retire l’émoji ; l’option d’icône par défaut retrouve le symbole du document.</p>'],
  ]];
  chapters.push(writingChapter);
  const comfortChapter = ['08 · Confort d’écriture · 1.3.7', [
    ['Garder le texte sélectionné visible', '<p>Quand tu ouvres la palette de couleur ou de surlignage, le repère bleu reste sur le texte sélectionné. Il reste visible pendant le choix d’une couleur personnalisée, même si le sélecteur prend le focus.</p><p>Quand tu appliques une couleur prédéfinie ou termines ton choix personnalisé, ce repère disparaît pour laisser voir le résultat. La couleur continue de s’appliquer en direct, sans bouton de validation supplémentaire.</p>'],
    ['Annuler sans rafraîchir le document', '<p>Ctrl + Z annule la dernière modification ; Ctrl + Y ou Ctrl + Maj + Z la rétablit. Les paragraphes et images qui n’ont pas changé restent en place. Le document entier n’est plus recréé lors de l’annulation.</p><p>Ces raccourcis utilisent aussi l’historique du texte quand le focus est resté sur un bouton de la barre de mise en forme ou dans son sélecteur de couleur. Les champs de saisie de taille ou de police conservent leur propre comportement.</p>'],
    ['Des crans de zoom plus fins', '<p>En mode Note, les boutons de zoom avancent maintenant par pas de 5 points : 100 %, 105 %, 110 %, etc. Ctrl + molette et le pincement sont deux fois moins sensibles ; les petits mouvements successifs restent pris en compte.</p><p>Le zoom reste visuel, de 50 % à 200 %. La taille réelle des caractères et l’impression ne changent pas. Clique sur le pourcentage pour revenir à 100 %.</p>'],
  ]];
  chapters.push(comfortChapter);
  function upgrade(box, uid, now) {
    if (!box?.isGuide || !box.root || box.guideVersion >= VERSION) return false;
    const stamp = now();
    const additions = [...(box.guideVersion < 2 ? [bookChapter] : []), ...(box.guideVersion < 3 ? [writingChapter] : []), comfortChapter];
    for (const chapter of additions) {
      const notes = chapter[1].map(([title, content]) => ({ id:uid('note'), type:'note', title, content, createdAt:stamp, modifiedAt:stamp }));
      box.root.children.push({ id:uid('folder'), type:'folder', title:chapter[0], children:notes, createdAt:stamp, modifiedAt:stamp });
    }
    box.guideVersion = VERSION; box.modifiedAt = stamp;
    return true;
  }
  function create(uid, now) {
    const stamp = now();
    const item = (type, title, extra) => ({ id: uid(type), type, title, createdAt: stamp, modifiedAt: stamp, ...extra });
    const folders = chapters.map(([title, notes]) => item('folder', title, { children: notes.map(([title, content]) => item('note', title, { content })) }));
    const root = item('folder', 'Guide MindSet', { children: folders });
    return { id: uid('box'), name: 'Guide MindSet', isGuide: true, guideVersion: VERSION, passwordHash: '', createdAt: stamp, modifiedAt: stamp, root, activeItemId: folders[0].children[0].id, expandedIds: [root.id, folders[0].id], selectedIds: [], bookmarkedIds: [], openTabIds: [], viewMode: 'tree', sortMode: 'custom', iconFolderId: root.id, searchQuery: '' };
  }
  root.MindSetGuide = { create, upgrade, VERSION };
  if (typeof module === 'object' && module.exports) module.exports = root.MindSetGuide;
})(typeof globalThis === 'object' ? globalThis : this);
